### ISSUE TITLE
Possible legal infringement?

### ISSUE THREAD

**Issue by erickwilder** [c-3po-org/c-3po#104]
Hello @AlexMost 

I've been looking for some ways to do translations using a similar workflow as I'm used to with GNU gettext in other environments (e.g: Python, PHP, Ruby) and I think c3po could find a very good balance between supporting it and also putting JS first.

I have a question and I hope you don't mind that I'm using this space here in the issue tracking for that. I also want to give a fair warning that it might be a bit controversial, but I do so in good faith.

**Does the name of the library can cause any possible future legal action?**
I really liked the name, just to be clear. It's awesome. But my concerns about it are towards _possible, future_ legal actions that it might have. I'm not a lawyer, but I guess that some of the people at Disney would not be pleased to see both the name of the character (C3PO) and the picture of it in the organization profile.
I'm asking this because every open source project I intend to use/support I do with a hope they'll be there for many years and that I could safely recommend in my work environment - which is not the case here. Unfortunately, as the gray areas appear on any legal aspects, most companies tend to be _in the safe side_. In this case, it is _not adopting_ a great library like this one.

**Comment by AlexMost** [comment]
Hello @erickwilder!

Thanks for the good words and your warning! The library already has some happy users and we are going to support it. So, it makes perfect sense to discuss what we can do, to prevent possible legal infringement and to make this library more attractive to adopt and contribute.

From this point we can do:
1. Discuss this issue with a lawyer (going to do that tomorrow, and share the results here).
2. Think about renaming the project and about the smooth migration to the new name/package/org. 

Feel free to suggest your ideas here! I am really glad that you like this library.

What do you think @MrOrz @vharitonsky @alxpy @tlrobinson ?

**Comment by MrOrz** [comment]
+1 for the active and positive advice.

Since project names that is as safe as "Jade" [changed their name](https://github.com/pugjs/pug/issues/2184) when needed, it would be great if we figure this out early and take actions when necessary.

**Comment by erickwilder** [comment]
Nice! I'm looking forward to it.

**Comment by AlexMost** [comment]
I have discussed this issue with lawyers in our company and they also recommended to think about the different name for the project. The main reason is that there is an official trademark with this name (you can check it here - http://www.wipo.int/madrid/monitor/en/ ). So, thanks again @erickwilder.

So, for now, we can start thinking about the new name for the project. I was thinking about that for some time, and all those names like `translation`, `localization`, `i18n` e.t.c are a little bit boring. So, my expectations from the new name are:

* short (3 - 5 characters).
* does not contain `translation`, `localization`, `i18n` in it's name.
* there should be no existing trademark with that name.
* available package on the npm.

Looking forward for your ideas :)

**Comment by dlazerka** [comment]
There is already a software product called c3p0: http://www.mchange.com/projects/c3p0/

**Comment by ShaneCurcuru** [comment]
There are a couple of websites with very useful trademark information that's focused at open source projects:

- http://fossmarks.org/
- http://twiki.org/cgi-bin/view/Blog/BlogEntry201207x1

The ASF has a detailed procedure for how they vet new names proposed for Apache projects - their goals may be subtly different than yours, but it may be useful to read through the "Research" steps to take when vetting a new project name.  (Tip: it's really helpful to do this yourself before you talk to the lawyer - often saves legal time!)

https://www.apache.org/foundation/marks/naming#namesearch

Good luck!

**Comment by AlexMost** [comment]
@ShaneCurcuru thanks a lot!

**Comment by erickwilder** [comment]
Are you open to suggestions for new names? If so, should we do this on this issue or open a new one?

**Comment by AlexMost** [comment]
@erickwilder for sure we are open for the new names. Here is a separate issue for that - https://github.com/c-3po-org/c-3po/issues/105
