### ISSUE TITLE
Sort order of msgids in translations.pot

### ISSUE THREAD

**Issue by Axbon** [c-3po-org/c-3po#11]
Hey,
We successfully run this tool in a project, works well. However, one thing that may be slightly inconvenient is if you version the template.pot file, the order of the strings are different from build to build even if no strings are changed. It may pose a problem in that it generates merge conflicts, could it be an idea to sort the **msgids**  alphabetically to mitigate this?

**Comment by MrOrz** [comment]
Found that there is an issue related to msgid order: https://github.com/c-3po-org/babel-plugin-c-3po/issues/48

**Comment by Axbon** [comment]
Oh neat there was another issues there. Yeah I agree, string locations would also work and in fact might be a better option since whoever does the translation could actually get a little bit of context, if the strings that are close to each other in the template file share a similar context ie (view or location in the app).

**Comment by AlexMost** [comment]
@Axbon wow, great to hear that someone already tried this tool) I was investigating this issue a little bit already and I agree that sorting option must be implemented. I am using [gettext-parser](https://github.com/smhg/gettext-parser) library for saving .po and .pot files and have an idea to make PR for that lib to support sorting option.

**Comment by AlexMost** [comment]
created PR for gettext-parser - https://github.com/smhg/gettext-parser/pull/31

**Comment by AlexMost** [comment]
this feature is already available in `0.2.0`. You can use `sortByMsgid : true` in config to enable this (will be documented soon). 

https://github.com/c-3po-org/babel-plugin-c-3po/pull/59
