### ISSUE TITLE
support gettext extracted comments

### ISSUE THREAD

**Issue by MrOrz** [c-3po-org/c-3po#12]
Extracted comments (see `--add-comments` part of [the gettext doc](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html), or [developer comments](http://docs.translatehouse.org/projects/localization-guide/en/latest/guide/project/howto.html#a-developer-comment)) can be helpful for developers to hint the translator about the translated string. It would be nice if we support such feature.

```js
/* this is foo */
const foo =  t`pen pineapple apple pen`;

const bar = /* hello world */ngettext(/* this is bar */ msgid`${n} time clicked`, `${n} times clicked`, n);

```

Could extracts to something like:

```
#. this is foo
#: some-file
msgid "pen pineapple apple pen"
msgstr ""

#. hello world
#. this is bar
#: some-file
msgid "${ 0 } time clicked"
msgid_plural "${ 0 } times clicked"
msgstr[0] ""
msgstr[1] ""
```

**Comment by AlexMost** [comment]
Agree, this one is already in todo list. Do you think we should extract all comments before translated string or with some special marker like:
```
/* trans: this is foo */
const foo =  t`pen pineapple apple pen`;
```

**Comment by MrOrz** [comment]
Seems that [`gettext --add-comments`](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html) has an optional "tag" argument. When tag is not specified it extracts all comments, and when a tag is specified, it only extracts comments with those tag.

**Comment by AlexMost** [comment]
started work on this here - https://github.com/c-3po-org/babel-plugin-c-3po/pull/56

**Comment by AlexMost** [comment]
you can try this feature in `0.1.0` version of babel-plugin-c3po

**Comment by MrOrz** [comment]
Thank you so much for the rapid response!

I am trying this out and [found a small issue](https://github.com/c-3po-org/babel-plugin-c-3po/pull/57). After fixing that it is working pretty well.

I have identified an edge case that is a little bit weird, though, expressed in a pseudo-test case below:

```js
    // in test_extract_developer_comments.js

    it.only('should extract each level of comments', () => {
        const input = dedent(`
        import { t } from 'c-3po';

        // comment4-3
        dispatch( /* comment4-2 */ someAction( /* comment4-1 */ t\`test4\` ))
        `);
        babel.transform(input, options);
        const result = fs.readFileSync(output).toString();
        console.log(result); // What should the result be?
    });
```

Currently the output of `result` is:

```
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"Plural-Forms: nplurals=2; plural=(n!=1);\n"

#.  comment4-2
msgid "test4"
msgstr ""
```

I was expecting `#. comment4-1`. `#. comment4-3\n#. comment4-2\n#. comment4-1` may be even better, but it may be hard to achieve this.

When `t` is put inside a function call, the `node` received by `applyExtractedComments()` becomes a `CallExpression` with the `TaggedTemplateExpression` as its only argument and `someAction` being the callee with a leading comment `comment4-2`.

The current status is a little bit confusing, and I think there might be a number of edge cases (like in the middle of string catenation, inside a template string interpolation) to consider.

**Comment by MrOrz** [comment]
I found that supporting `#. comment4-1` is not easier than directly supporting `#. comment4-3\n#. comment4-2\n#. comment4-1`.

**Comment by AlexMost** [comment]
Thanks, I have merged your PR because it fixes bug with `#. comment4-1` and also who knows maybe someone will find the use case for the recursive comments. Will update doc soon.

**Comment by MrOrz** [comment]
I have tried it out in my code. I find recursive comments useful when commenting a group of keys that should be given same comments. Instead of prepending comments before each `t()`, I did something like:

```js
export const keyToNames = (key) => {
  // t: Action name in page OOO.
  const MAPPING = {
    key1: t`Something`,
    key2: t`Another Thing`,
    key3: t`Yet another thing`,
  };

  return MAPPING[key] ? MAPPING[key] : key;
};
```

```js
export const OPTIONS = /* t: option names */ fromJS([
  {label: t`option 1`, value: 1}, // ...
])
```

**Comment by AlexMost** [comment]
makes sense
