### ISSUE TITLE
Hello from es2015-i18n-tag

### ISSUE THREAD

**Issue by skolmer** [c-3po-org/c-3po#18]
Hey there, 
I'm the author of [es2015-i18n-tag](http://i18n-tag.kolmer.net). I just stumbled across your implementation of a translation library based on ES6 template tags. 
Just wanted to say that I'm happy this idea gets some more attention. 
Especially your progress on pluralization looks interesting. How about joining forces to build a more feature rich implementation of an i18n template tag?

By the way, I like the name of your lib. It sounds much better than es2015-i18n-tag :)

Best regards
Steffen

**Comment by AlexMost** [comment]
Hey) Happy to hear that! Looked through your lib and seems like our solutions have a lot in common. Do you suggest to start a new project and to merge functionalities?

**Comment by skolmer** [comment]
It could be worth to take a look at the pros and cons of both libs and build a new implementation based on these observations. But I'm not sure if I am able to invest the required time right now. Another approach could be to share features across both libraries. i18n-tag-schema for example could be a useful extension for c-3po. 
My main focus is to bring the whole concept of template tag based translations forward. So If there are parts where a cooperation of both projects can bring any progress, I'm open to talk :)

**Comment by smercadomx** [comment]
+1 for i18n-tag-schema.

**Comment by AlexMost** [comment]
@smercadomx Thanks, for your feedback! Can you please provide some generic workflow with `c-3po` and `i18n-tag-schema`, and how it can be helpful to you?

**Comment by AlexMost** [comment]
seems like 2 projects are about the usage of template tags but with different workflows. c-3po is all about integration with `gettext`workflow. For now, I can't see how i18n-tag-schema will help with this. Think we can close this issue for now. Feel free to create other issues with propositions.
