### ISSUE TITLE
Extract variables names to placeholders in .po and .pot files

### ISSUE THREAD

**Issue by AlexMost** [c-3po-org/c-3po#20]
Example:
```js
t`Hello ${ username}
```
For now this will be extracted to
```
msgid "Hello ${ 0 }"
```

This behaves so because we are missing variable names information while resolving translations at the runtime. (details described [here](https://c-3po.js.org/why-use-msgid-for-ngettext.html)).

But what if we will transform our translations object (json with translations) in form of `Hello ${ username }` to `Hello ${ 0 }` in the runtime. This operation will be not so hard to perform (traverse tree and clone). And with this solution we will have the best of 2 worlds:

1. The translator will see the variables names (provides more context for the translator).
2. Translations will be working without transpile because we will transform our translations obj to the format that works now.
3. Babel plugin has information about variable names also.

@MrOrz @alxpy

**Comment by alxpy** [comment]
As for me, it sounds good!
Additionally we can use my old PR (https://github.com/c-3po-org/babel-plugin-c-3po/pull/54)

**Comment by MrOrz** [comment]
:+1: LGTM!

**Comment by AlexMost** [comment]
Already done by @alxpy. Greate job. This feature is available in plugin and lib in `0.4.0` version.
