### ISSUE TITLE
extensions API

### ISSUE THREAD

**Issue by AlexMost** [c-3po-org/c-3po#22]
As it was mentioned [here](https://github.com/c-3po-org/c-3po/issues/3#issuecomment-285363024), some new features that we want to add to c-3po will require extra dependencies. I am worried about keeping the core functionality as generic as possible. 

In case that is described in the link above there is a feature request for `react.js` library which adds `react` and `babel-preset-react` to the project dependencies. 

So maybe it is reasonable to have an ability to extend *c-3po library* and *c-3po plugin* in a way that all extra dependencies will be installed only if you need them with a separate extension package. 

### Basic workflow for extensions:

1. There will be a separate package `c-3po-react`. So you need to install it separately if you need `rt` tag functionality.

2. `c-3po-react` package will expose functions (tags) for wrapping translations. (`rt` tag for instance).
   This must work without transpile step.
    ```jsx
    import { rt } from 'c-3po-react'
    rt`Click ${<a href="">here</a>}`
    ```
3. Aditionaly we must upgrade `babel-plugin-c-3po` to be extensible via configuration. This can be done in something like this way:
    *.babelrc*
    ```js
    plugins: [['c-3po', { extensions: ['c-3po-react'] }]]
    ```
    After this config babel plugin should be able to extract, validate and resolve translations inside `rt` tag.

In general, extensions would be easy to implement because `c-3po` already uses all extractor functions as extensions. You can look at how `t` tag is implemented - [tag-gettext src](https://github.com/c-3po-org/babel-plugin-c-3po/blob/master/src/extractors/tag-gettext.js)

Current rough implementation for `rt` tag is here - https://github.com/c-3po-org/c-3po/pull/21
Want to hear your feedback guys @alxpy @MrOrz ? What do you think?

**Comment by MrOrz** [comment]
LGTM :+1:
btw, what about `jt`? Should it be a plugin as well? Or it can stay in the c3po core?
Feeling like that other extensions can extend `jt`'s array output to fit their needs.

**Comment by AlexMost** [comment]
I think `jt` is something that can be in c3po core. Ok, so I will start my work on extensions.

**Comment by alxpy** [comment]
I think this is the right way :+1:

**Comment by AlexMost** [comment]
seems like `jt` is doing well here, so there is no reason to complicate internal API with extensions by now.
