### ISSUE TITLE
Update doc with new extraction rules

### ISSUE THREAD

**Issue by AlexMost** [c-3po-org/c-3po#32]
As we will merge this PR's:

https://github.com/c-3po-org/babel-plugin-c-3po/pull/71

https://github.com/c-3po-org/c-3po/pull/29

We should update doc properly:

- [x] https://c-3po.js.org/tag-gettext--t-.html
- [x] https://c-3po.js.org/ngettext.html
- [x] https://c-3po.js.org/gettext.html
- [x] https://c-3po.js.org/tag-ngettext--nt-.html
- [x] https://c-3po.js.org/quick-start.html
- [x] https://c-3po.js.org/why-use-msgid-for-ngettext.html

**Comment by alxpy** [comment]
@AlexMost @MrOrz  I was going to do it, but I don't know when I'll have time for it. It would be cool that someone of you helped me with this =) Or I'll do it myself, but later)
