### ISSUE TITLE
doc for jt tag

### ISSUE THREAD

**Issue by AlexMost** [c-3po-org/c-3po#35]
Since we have support for `jt` it would be nice to document it in our docs.

**Comment by AlexMost** [comment]
done https://c-3po.js.org/jsx-tag-jt.html @MrOrz @alxpy

**Comment by MrOrz** [comment]
Thanks for the doc! Sorry that I did not have time working on the doc earlier.
Based on the original doc, I have made some modifications to the doc to clarify how `jt` works:
https://github.com/c-3po-org/c-3po/pull/38

**Comment by AlexMost** [comment]
Np, thanks for the clarification to doc.
