### ISSUE TITLE
Remove nt tag

### ISSUE THREAD

**Issue by AlexMost** [c-3po-org/c-3po#50]
We have an experimental `nt` function for working with plural forms - https://c-3po.js.org/tag-ngettext--nt-.html.
So, the question is do we really need to support multiple functions to handle plurals? As for me, I'm ok with `ngettext`. I suggest to remove `nt` tag.
What do you think? @alxpy @MrOrz

**Comment by alxpy** [comment]
I agree

**Comment by MrOrz** [comment]
I always use ngettext for plural forms. I think is is ok to drop it.

Alex Kuzmenko <notifications@github.com> 於 2017年4月13日 週四 下午5:40 寫道：

**Comment by AlexMost** [comment]
ok, let's drop it.

**Comment by alxpy** [comment]
![fire](https://media.giphy.com/media/YA6dmVW0gfIw8/giphy.gif)
