### ISSUE TITLE
no POT generated when extracting stuff

### ISSUE THREAD

**Issue by AlexMost** [c-3po-org/c-3po#9]
- caching issue

**Comment by MrOrz** [comment]
Recently I found that if the user has babel-loader's `cacheDirectory` turned on, no POT files will be generated when extracting stuff, nor does newly translated PO files gets applied. Thus `cacheDirectory` must be turned off when extracting strings and generating bundles with translations.

Maybe this should be noted in somewhere like troubleshooting section?

Before:
```js
var c3po = {};
// ... following instructions inside https://c-3po.js.org/localization-with-webpack-and-c-3po.html

// ...
rules: [
    {
        test: /\.(js|jsx)$/,
        use: { loader: 'babel-loader', options: {plugins: ['c-3po', c3po], cacheDirectory: true } }
    }
]
```

After: 
```js
var c3po = {};
// ... following instructions inside https://c-3po.js.org/localization-with-webpack-and-c-3po.html

// ...
rules: [
    {
        test: /\.(js|jsx)$/,
        use: { loader: 'babel-loader', options: {plugins: ['c-3po', c3po], cacheDirectory: !(c3po.extract || c3po.resolve) } }
    }
]
```

**Comment by AlexMost** [comment]
oh, thanks for reporting this issue. Looked through babel-loader configuration [here](https://github.com/babel/babel-loader) maybe we can also solve this problem by cacheIdentifier setting. Will try it today.

**Comment by MrOrz** [comment]
I have tried `cacheIdentifier` before.
It failed to detect PO file change automatically, compiling to the same bundle no matter how I change PO files.
We have to encode PO file checksum in the `cacheIdentifier` in order to make it work; for me, disable cache entirely is much simpler XD

**Comment by AlexMost** [comment]
@MrOrz what do you think - https://github.com/c-3po-org/c-3po/pull/13 ?

**Comment by AlexMost** [comment]
https://c-3po.js.org/why-po-is-not-updated.html
