### ISSUE TITLE
Allow any expression in localized strings?

### ISSUE THREAD

**Issue by tlrobinson** [c-3po-org/c-3po#95]
Only allowing variables and property accesses in localized strings feels limiting. Would it be possible to support any expression, and instead of using the expression in the extracted string use positional references like `hello {0}`, as is used in many other `gettext` implementations?

**Comment by AlexMost** [comment]
From the very beginning `c-3po` behaved so) But, we found those numbers in translations a little bit uninformative and decided to change that behavior - https://github.com/c-3po-org/c-3po/issues/20. But, I think we can implement some kind of configuration that will switch between this 2 modes. @MrOrz @vharitonsky @alxpy What do you think about that?

**Comment by alxpy** [comment]
> implement some kind of configuration that will switch between this 2 modes
+1

**Comment by MrOrz** [comment]
Thumbs up for supporting expressions.

In our use case we has done a lot of things like:
```
const updatedAtStr = moment(data.get('updatedAt')).format('lll')
return <span>{t`${updatedAtStr} updated`}</span>
```

If expressions are supported, it would free us from verbose variable assignments.

However, a downside may be that developers will put complex expressions within `${...}` and may increase the opportunity that translators modifies them accidentally. A switch between the 2 modes sounds a great idea, with the current behavior (blocks complex expressions) be the default, and let those who feeling adventurous flip the switch :)

**Comment by AlexMost** [comment]
Created 2 separate issues for implementing this setting in the library and the babel-plugin, feel free to review them and leave your comments and suggestions. Also, added those issues to `0.8.0` milestone.

**Comment by tlrobinson** [comment]
Great, thanks!

I agree the variable name can add useful context. However the problem we're running into is with JSX it often requires pulling out a lots of expressions just for i18n purposes e.x.

```javascript
return <div>{jt`Hello ${<strong>{user}</strong>}.`}</div>
```

becomes

```javascript
const userElement = <strong>{user}</strong>;
return <div>{jt`Hello ${userElement}.`}</div>
```

And that's just a simple case.

On the other hand, nested JSX + i18n tagged strings gets messy quickly so sometimes it's still best to pull out parts of the string into variables.

I wonder if there's a better solution for JSX. I've found that people new to this accidentally move JSX into the string, which results in HTML tags appear in the UI:

```javascript
return <div>{jt`Hello <strong>${user}</strong>`}</div>
```

A magic component that lets us leave most of the JSX the same would be neat:

```javascript
return <div><T msgid="hello_string">Hello <strong>{user}</strong>.</T></div>
```

And it would automatically extract a string like `Hello {user}.`.

```javascript
return <div><T>Hello <strong>Mr. {first_name}</strong>.</T></div>
```

Just extracting `Hello Mr. {user}.` loses the context to know if the `Mr.` goes inside or outside the `<strong>`.

Maybe an area for exploration though.

**Comment by MrOrz** [comment]
@tlrobinson Thanks for providing more use cases!

I totally agree that current `jt` implementation will force developers to separate tag translations from the original context. Personally I am using developer comments to denote the context in the extracted constants. For example:

```
const userElem = <strong key="user">{/* t: Hello, ~ */ t`Mr. {firstName}`}</strong>
return <div>{/* t: ~ Mr.X */ jt`Hello ${userElem}`}</div>
```

A bit verbose and manual, but it somehow worked.

Personally I see `jt` as a sub-optimal approach to support strings containing JSX elements in a way that introduces no dependencies (and easier to implement, too).

The [original discussion](https://github.com/c-3po-org/c-3po/issues/3) also includes @AlexMost 's initial proposal on supporting React translations. [`rt` PR](https://github.com/c-3po-org/c-3po/pull/21) was his attempt in its implementation. Maybe we can continue the discussions here?

**Comment by AlexMost** [comment]
@tlrobinson that is a good question) 

Here is a list of features that I wish to have in a resulting solution:

1. Allow to nest jsx elements inside translation.
2. Possibility to place `click` and `here` from `Click ${ <a>here</a>}` in one translatable msgid.
1. It should work without transpile step (just with pure c-3po library)
2. HTML (jsx) tags should not leak to the `.po` files.
3. This feature should not force us to include react as a dependency to the original library.

As @MrOrz had mentioned above, there was some experiment with `rt` tag [here](https://github.com/c-3po-org/c-3po/issues/3) and `jt` appeared much simple and reliable alternative. 

But I also agree that we should find a more advanced solution for `jsx`. What do you think about implementing something similar to this approach - https://blog.sentry.io/2016/01/07/react-i18n.

# Short example
In general, solution can look like this:
```jsx
<p><small>{tct(t`Already have things setup? [link:Get your DSN].`, {
  link: <a onClick={this.toggleDsn} />
})}</small></p>
```
Translator will get this in the `.po` file
```
msgid: "Already have things setup? [link:Get your DSN]."
```
And the rest of work will be done by `tct` helper function in a runtime - `Get your DSN` will be placed as a `children` of the link component. This helper function can be placed somewhere in a separate package. Theoretically, this DSL - `[link: Get your DSN]` can work with any framework (not specific to React).

What do you think?

**Comment by AlexMost** [comment]
Another idea came to my mind) What if we can mark different parts of the same string?

The example above will look like this:

```jsx
<p><small>
{t`mark:Already have things setup?`}<a onClick={this.toggleDsn>{t`mark:Get your DSN.}</a>
</small></p>
```
```
msgid: " | Already have things setup? | Get your DSN. | "
```
But it's only my assumption, need to check that.

we can also use `t` as a function call instead of adding mark inside the translatable string.

**Comment by AlexMost** [comment]
So, with `numberedExpression` setting we can use any expression inside the translations. That task is done in `babel-plugin-c-3po@8.0.0-0`. Will add docs and will merge in master soon. But unfortunately, we still haven't decided the best flow with `jsx`. Looking forward for your suggestions in a separate issue.
